namespace CeskyRozhlasMiner.Lib.Common
{
    public enum RozhlasStation
    {
        Zurnal,
        Dvojka,
        Vltava,
        ZurnalSport,
        Wave,
        Ddur,
        Jazz,
        Pohoda,
        Plus,
        Junior,
        Cro7,
        CeskeBudejovice,
        HradecKralove,
        KarlovyVary,
        Liberec,
        Olomouc,
        Ostrava,
        Pardubice,
        Plzen,
        Regina,
        StredniCechy,
        Sever,
        Vysocina,
        Zlin,
    }
}
